name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn run test
    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew build
