name: Android CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CODEPUSH_ANDROID_STAGING_KEY: ${{ secrets.CODEPUSH_ANDROID_STAGING_KEY }}
      CODEPUSH_ANDROID_PROD_KEY: ${{ secrets.CODEPUSH_ANDROID_PROD_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn run test
      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew
      - name: Build with Gradle
        run: yarn staging-android
